[package]
name = "game_components_token"
version = "1.5.1"
edition = "2024_07"


[cairo]
sierra-replace-ids = true

[dependencies]
starknet.workspace = true
openzeppelin_token = "1.0.0"
openzeppelin_introspection = "1.0.0"
# Game components dependencies
game_components_minigame = { path = "../minigame" }
game_components_metagame = { path = "../metagame" }
game_components_utils = { path = "../utils" }
game_components_test_starknet = { path = "../test_starknet" }

[scripts]
test = "snforge test"

[lib]

[[target.starknet-contract]]
sierra = true
casm = true