[package]
name = "game_components_metagame"
version.workspace = true
edition.workspace = true

[lib]

[cairo]
sierra-replace-ids = true

[dependencies]
starknet.workspace = true
game_components_token = { path = "../token" }
game_components_utils = { path = "../utils" }
openzeppelin_introspection = "1.0.0"
