[package]
name = "game_components_metagame"
version.workspace = true
edition.workspace = true

[lib]

[cairo]
sierra-replace-ids = true

[dependencies]
game_components_denshokan = { path = "../denshokan" }
game_components_utils = { path = "../utils" }
dojo = { git = "https://github.com/dojoengine/dojo", tag = "v1.5.1" }
openzeppelin_introspection = "1.0.0"

[[target.starknet-contract]]
build-external-contracts = ["dojo::world::world_contract::world"]

[dev-dependencies]
cairo_test = "=2.10.1"
dojo_cairo_test = { git = "https://github.com/dojoengine/dojo", tag = "v1.5.0" }
