[package]
name = "test_dojo"
version = "1.5.1"
edition = "2024_07"

[dependencies]
starknet = "2.10.1"
dojo = { git = "https://github.com/dojoengine/dojo", tag = "v1.5.1" }
openzeppelin_introspection = "1.0.0"

# Local component dependencies
game_components_minigame = { path = "../minigame" }
game_components_metagame = { path = "../metagame" }
game_components_minigame_token = { path = "../minigame_token" }
game_components_utils = { path = "../utils" }

[[target.starknet-contract]]
build-external-contracts = ["dojo::world::world_contract::world"]

[dev-dependencies]
cairo_test = "=2.10.1"
dojo_cairo_test = { git = "https://github.com/dojoengine/dojo", tag = "v1.5.1" }