[package]
name = "game_components_test_starknet"
version.workspace = true
edition.workspace = true

[dependencies]
starknet.workspace = true
openzeppelin_introspection = "1.0.0"
game_components_metagame = { path = "../metagame" }
game_components_minigame = { path = "../minigame" }
game_components_utils = { path = "../utils" }

[scripts]
test = "snforge test"

[dev-dependencies]
cairo_test = "2.10.1"
snforge_std = "0.45.0"