[package]
name = "game_components_denshokan"
version.workspace = true
edition.workspace = true

[lib]

[cairo]
sierra-replace-ids = true

[dependencies]
game_components_minigame = { path = "../minigame" }
